# Generated by Django 5.2.9 on 2026-02-02 01:24

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nhóm xét nghiệm')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm xét nghiệm',
                'verbose_name_plural': 'Các nhóm xét nghiệm',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ lấy mẫu'), ('SAMPLING', 'Đã lấy mẫu'), ('PROCESSING', 'Đang thực hiện'), ('COMPLETED', 'Đã có kết quả'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú lâm sàng')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_created', to='authentication.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='reception.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabOrderDetail',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='lis.laborder')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu xét nghiệm',
                'verbose_name_plural': 'Các chi tiết phiếu xét nghiệm',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('value_string', models.CharField(max_length=255, verbose_name='Kết quả (Chuỗi)')),
                ('value_numeric', models.FloatField(blank=True, null=True, verbose_name='Kết quả (Số)')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='Bất thường')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Nguy hiểm (Critical)')),
                ('abnormal_flag', models.CharField(blank=True, help_text='H=High, L=Low, HH=Critical High, LL=Critical Low', max_length=10, null=True, verbose_name='Cờ bất thường')),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên máy xét nghiệm')),
                ('result_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian có kết quả')),
                ('is_verified', models.BooleanField(default=False, help_text='Bác sĩ xét nghiệm đã xác nhận kết quả', verbose_name='Đã duyệt')),
                ('verified_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('verification_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú khi duyệt')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lis.laborderdetail')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_processed', to='authentication.staff', verbose_name='Kỹ thuật viên thực hiện')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified', to='authentication.staff', verbose_name='Bác sĩ duyệt kết quả')),
            ],
            options={
                'verbose_name': 'Kết quả xét nghiệm',
                'verbose_name_plural': 'Các kết quả xét nghiệm',
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('barcode', models.CharField(help_text='Barcode dán trên ống nghiệm', max_length=50, unique=True, verbose_name='Mã vạch')),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Máu'), ('URINE', 'Nước tiểu'), ('STOOL', 'Phân'), ('SPUTUM', 'Đờm'), ('CSF', 'Dịch não tủy'), ('TISSUE', 'Mô'), ('SWAB', 'Dịch ngoáy'), ('OTHER', 'Khác')], default='BLOOD', max_length=20, verbose_name='Loại mẫu')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ lấy mẫu'), ('COLLECTED', 'Đã lấy mẫu'), ('IN_TRANSIT', 'Đang vận chuyển'), ('RECEIVED', 'Lab đã nhận'), ('PROCESSING', 'Đang xét nghiệm'), ('REJECTED', 'Mẫu bị từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('collection_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lấy mẫu')),
                ('collection_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú khi lấy mẫu')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lab nhận mẫu')),
                ('rejection_reason', models.TextField(blank=True, help_text='VD: Mẫu bị vỡ, không đủ lượng, sai định danh...', null=True, verbose_name='Lý do từ chối mẫu')),
                ('rejected_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian từ chối')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to='authentication.staff', verbose_name='Người lấy mẫu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lis.laborder', verbose_name='Phiếu xét nghiệm')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_received', to='authentication.staff', verbose_name='Nhân viên nhận mẫu')),
            ],
            options={
                'verbose_name': 'Mẫu bệnh phẩm',
                'verbose_name_plural': 'Các mẫu bệnh phẩm',
                'ordering': ['-collection_time'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã xét nghiệm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên xét nghiệm')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đơn vị')),
                ('min_limit', models.FloatField(blank=True, null=True, verbose_name='Chỉ số thấp nhất (Bình thường)')),
                ('max_limit', models.FloatField(blank=True, null=True, verbose_name='Chỉ số cao nhất (Bình thường)')),
                ('panic_low', models.FloatField(blank=True, null=True, verbose_name='Ngưỡng nguy hiểm thấp')),
                ('panic_high', models.FloatField(blank=True, null=True, verbose_name='Ngưỡng nguy hiểm cao')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá tiền')),
                ('turnaround_time', models.IntegerField(blank=True, help_text='Thời gian dự kiến để có kết quả, tính bằng phút', null=True, verbose_name='Thời gian trả kết quả (phút)')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='lis.labcategory', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Chỉ số xét nghiệm',
                'verbose_name_plural': 'Các chỉ số xét nghiệm',
            },
        ),
        migrations.AddField(
            model_name='laborderdetail',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='lis.labtest'),
        ),
        migrations.AlterUniqueTogether(
            name='laborderdetail',
            unique_together={('order', 'test')},
        ),
    ]
