# Generated by Django 5.2.9 on 2026-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ lấy mẫu'), ('SAMPLING', 'Đã lấy mẫu'), ('PROCESSING', 'Đang thực hiện'), ('COMPLETED', 'Đã có kết quả (Chờ duyệt)'), ('VERIFIED', 'Đã duyệt'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
    ]
