# Generated by Django 5.2.9 on 2026-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lis', '0002_add_verified_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborderdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='laborderdetail',
            name='service_name',
            field=models.CharField(blank=True, help_text='Tên của ServiceList bên lâm sàng đã chỉ định (VD: Xét nghiệm đường huyết)', max_length=255, null=True, verbose_name='Dịch vụ gốc'),
        ),
    ]
