"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from decouple import config, Csv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-bg4r5r+2r*h8vd05(hsn4hel)bf8rg0x+yev)++*t9gul9bhja')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server — must be before django.contrib.staticfiles
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Django Channels for WebSocket
    'apps.api',  # Streaming API 
    'apps.ai_engine.agents',
    'apps.ai_engine.rag_service',
    'apps.core_services.core',
    'apps.core_services.appointments',
    'apps.core_services.authentication',
    'apps.core_services.insurance_mock',
    'apps.core_services.patients',
    'apps.medical_services.emr',
    'apps.medical_services.inpatients',
    'apps.medical_services.lis',
    'apps.medical_services.ris',
    'apps.medical_services.pharmacy',      # New
    'apps.medical_services.paraclinical',  # New
    'apps.core_services.departments',
    'apps.core_services.reception',
    'apps.core_services.qms',  # Queue Management System
    'apps.core_services.billing',  # Billing & Payment
    'apps.core_services.kiosk',  # Kiosk Tự Phục Vụ
    'apps.core_services.scanner',  # Remote Scanner WebSocket
    'apps.interoperability',  # Liên thông Y tế (FHIR / DICOM)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS - phải đặt đầu tiên
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB', default='his_database'),
        'USER': config('POSTGRES_USER', default='postgres'),
        'PASSWORD': config('POSTGRES_PASSWORD', default='postgres'),
        'HOST': config('POSTGRES_HOST', default='localhost'),
        'PORT': config('POSTGRES_PORT', default='5432'),
    }
}

# Redis Configuration
# https://redis.io/docs/
# Redis Configuration
# https://redis.io/docs/
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)
REDIS_AGENT_MEMORY_TTL = config('REDIS_AGENT_MEMORY_TTL', default=86400, cast=int)

# Django Channels — Channel Layers (uses Redis above)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# RAG Service Configuration
import os
RAG_VECTOR_DB = config('RAG_VECTOR_DB', default='pgvector')
RAG_EMBEDDING_PROVIDER = config('RAG_EMBEDDING_PROVIDER', default='google')
RAG_EMBEDDING_MODEL = config('RAG_EMBEDDING_MODEL', default='')
RAG_EMBEDDING_DIMENSION = config('RAG_EMBEDDING_DIMENSION', default=768, cast=int)
RAG_TOP_K_RESULTS = config('RAG_TOP_K_RESULTS', default=5, cast=int)
RAG_SIMILARITY_THRESHOLD = config('RAG_SIMILARITY_THRESHOLD', default=0.5, cast=float)

# Google AI Configuration (if using Google embeddings)
GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')

# SSE Streaming Configuration
SSE_KEEPALIVE_INTERVAL = config('SSE_KEEPALIVE_INTERVAL', default=15, cast=int)  # seconds
SSE_MAX_STREAM_DURATION = config('SSE_MAX_STREAM_DURATION', default=120, cast=int)  # seconds

# Interoperability Settings (FHIR / DICOM)
FHIR_SERVER_URL = config('FHIR_SERVER_URL', default='')
PACS_SERVER_URL = config('PACS_SERVER_URL', default='')
INTEROP_MOCK_MODE = config('INTEROP_MOCK_MODE', default=True, cast=bool)

# Channels / WebSocket Configuration
ASGI_APPLICATION = 'config.asgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'authentication.User'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Layer 3: Rate Limiting cho Kiosk endpoints
    'DEFAULT_THROTTLE_RATES': {
        'kiosk': '10/min',  # Max 10 requests/phút per IP
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# ── Celery Configuration ─────────────────────────────────────────────
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'

# ── Media files (TTS audio, uploads) ─────────────────────────────────
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# ── TTS Configuration ────────────────────────────────────────────────
TTS_VOICE = config('TTS_VOICE', default='vi-VN-HoaiMyNeural')
TTS_AUDIO_DIR = 'audio/tts'  # relative to MEDIA_ROOT
TTS_PRE_GENERATE_COUNT = config('TTS_PRE_GENERATE_COUNT', default=5, cast=int)
