# Generated by Django 5.2.9 on 2026-01-21 14:27

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('departments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('visit_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('CHECK_IN', 'Đang Check-in/Khai báo'), ('TRIAGE', 'Đang phân luồng'), ('WAITING', 'Đang chờ bác sĩ'), ('IN_PROGRESS', 'Đang khám'), ('PENDING_RESULTS', 'Chờ kết quả CLS'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='CHECK_IN', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Bình thường'), ('PRIORITY', 'Ưu tiên (Người già/Trẻ em)'), ('EMERGENCY', 'Cấp cứu (Code Red)')], default='NORMAL', max_length=20)),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('ai_prediction', models.JSONField(blank=True, null=True)),
                ('medical_summary', models.TextField(blank=True, null=True)),
                ('queue_number', models.IntegerField()),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to='authentication.staff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_visits', to='departments.department')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
