# Generated by Django 5.2.9 on 2026-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Bình thường'), ('ONLINE_BOOKING', 'Đặt lịch hẹn'), ('PRIORITY', 'Ưu tiên (Người già/Trẻ em)'), ('EMERGENCY', 'Cấp cứu (Code Red)')], default='NORMAL', max_length=20),
        ),
    ]
