# Generated by Django 5.2.9 on 2026-02-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('reception', '0003_alter_visit_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do khám'),
        ),
        migrations.AddField(
            model_name='visit',
            name='confirmed_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_visits', to='departments.department', verbose_name='Khoa xác nhận'),
        ),
        migrations.AddField(
            model_name='visit',
            name='recommended_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_visits', to='departments.department', verbose_name='Khoa AI đề xuất'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_ai_response',
            field=models.TextField(blank=True, null=True, verbose_name='Phản hồi AI'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã phân luồng'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_confidence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Độ tin cậy (%)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
