# Generated by Django 5.2.9 on 2026-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_visit_chief_complaint_visit_confirmed_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='vital_signs',
            field=models.JSONField(blank=True, null=True, verbose_name='Chỉ số sinh hiệu'),
        ),
    ]
