# Generated by Django 5.2.9 on 2026-02-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_visit_vital_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='triage_method',
            field=models.CharField(blank=True, choices=[('AI', 'AI phân luồng'), ('MANUAL', 'Thủ công (Reception)')], max_length=10, null=True, verbose_name='Cách phân luồng'),
        ),
    ]
