# Generated by Django 5.2.9 on 2026-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_visit_triage_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='triage_key_factors',
            field=models.JSONField(blank=True, null=True, verbose_name='Cơ sở phân luồng'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_matched_departments',
            field=models.JSONField(blank=True, null=True, verbose_name='Khoa phù hợp (AI)'),
        ),
    ]
