# Generated by Django 5.2.9 on 2026-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_visit_triage_key_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='pending_merge',
            field=models.BooleanField(default=False, help_text='BN cấp cứu chưa xác định danh tính, cần gộp sau', verbose_name='Chờ gộp hồ sơ'),
        ),
    ]
