# Generated by Django 5.2.9 on 2026-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_visit_pre_triage_summary_vital_sign_recommendations_triage_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Bình thường'), ('ONLINE_BOOKING', 'Đặt lịch hẹn'), ('PRIORITY', 'Ưu tiên'), ('EMERGENCY', 'Cấp cứu'), ('SERVICE', 'Dịch vụ'), ('ELDERLY', 'Cao tuổi'), ('CHILD', 'Trẻ em')], default='NORMAL', max_length=20),
        ),
    ]
