# Generated by Django 5.2.9 on 2026-03-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_alter_visit_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='insurance_benefit_rate',
            field=models.IntegerField(blank=True, help_text='Phần trăm BHYT chi trả (VD: 80 → BHYT trả 80%, BN trả 20%). null = không có BHYT', null=True, verbose_name='Mức hưởng BHYT (%)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='insurance_card_expire',
            field=models.DateField(blank=True, help_text='Ngày hết hạn thẻ BHYT', null=True, verbose_name='HSD thẻ BHYT'),
        ),
        migrations.AddField(
            model_name='visit',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='Mã thẻ BHYT tại thời điểm đăng ký lượt khám', max_length=20, null=True, verbose_name='Mã thẻ BHYT'),
        ),
    ]
