# Generated by Django 5.2.9 on 2026-03-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_visit_insurance_benefit_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('CHECK_IN', 'Đang Check-in/Khai báo'), ('TRIAGE', 'Đang phân luồng'), ('WAITING', 'Đang chờ bác sĩ'), ('IN_PROGRESS', 'Đang khám'), ('PENDING_RESULTS', 'Chờ kết quả CLS'), ('PENDING_PAYMENT', 'Chờ thanh toán'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='CHECK_IN', max_length=20),
        ),
    ]
