# Generated by Django 5.2.9 on 2026-03-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0012_add_pending_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='pre_triage_summary',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='triage_hints',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vital_sign_recommendations',
        ),
    ]
