# Generated by Django 5.2.9 on 2026-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_remove_visit_pre_triage_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='pre_triage_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt trước khám (AI)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_hints',
            field=models.TextField(blank=True, null=True, verbose_name='Gợi ý phân luồng (AI)'),
        ),
        migrations.AddField(
            model_name='visit',
            name='vital_sign_recommendations',
            field=models.JSONField(blank=True, null=True, verbose_name='Chỉ định sinh hiệu cần đo (AI)'),
        ),
    ]
