# Generated by Django 5.2.9 on 2026-01-25 13:10

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('departments', '0001_initial'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('appointment_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Đã lên lịch'), ('CHECKED_IN', 'Đã tiếp đón'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy'), ('NO_SHOW', 'Không đến')], default='SCHEDULED', max_length=20)),
                ('appointment_type', models.CharField(choices=[('NEW', 'Khám mới'), ('RE_EXAM', 'Tái khám'), ('TELEHEALTH', 'Tư vấn từ xa')], default='NEW', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('reason_for_visit', models.TextField()),
                ('queue_number', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='departments.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='authentication.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('visit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_source', to='reception.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentChat',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('need_staff_response', models.BooleanField(default=False)),
                ('sender', models.CharField(choices=[('STAFF', 'Nhân viên y tế'), ('PATIENT', 'Bệnh nhân'), ('AGENT', 'Agent hỗ trợ khách hàng')], max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='appointments.appointment')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_chats', to='authentication.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
