# Generated by Django 5.2.9 on 2026-02-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_slot_end',
            field=models.DateTimeField(blank=True, help_text='VD: Nếu hẹn 08:00-08:15, đây là 08:15', null=True, verbose_name='Thời gian kết thúc khung giờ'),
        ),
    ]
