# Generated by Django 5.2.9 on 2026-01-28 16:30

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='Tên định danh của Agent (VD: Bác sĩ AI Khoa Nhi)', max_length=100)),
                ('role', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('TRIAGE', 'Triage'), ('CLINICAL', 'Clinical'), ('CORE', 'Core')], default='CORE', max_length=20)),
                ('model_name', models.CharField(choices=[('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash')], default='gemini-2.0-flash', max_length=30)),
                ('temperature', models.FloatField(default=0.7, help_text='Độ sáng tạo (0.0 - 1.0)')),
                ('system_instructions', models.TextField(blank=True, help_text='Prompt hướng dẫn hành vi cốt lõi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('collection_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('action', models.TextField(help_text='Mô tả hành động hoặc User Query')),
                ('input_token', models.IntegerField(default=0)),
                ('output_token', models.IntegerField(default=0)),
                ('latency', models.FloatField(help_text='Thời gian phản hồi (giây)')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.agentprofile')),
                ('vector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_logs', to='agents.vectorstore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
