# Generated by Django 5.2.9 on 2026-01-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorstore',
            name='dimensions',
            field=models.IntegerField(default=768, help_text='Kích thước vector (VD: 768)'),
        ),
        migrations.AddField(
            model_name='vectorstore',
            name='embedding_model',
            field=models.CharField(default='', help_text='Tên model (VD: )', max_length=100),
        ),
    ]
