# Generated by Django 5.2.9 on 2026-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlog',
            name='execution_details',
            field=models.JSONField(blank=True, default=dict, help_text='Chi tiết thực thi: reasoning traces, tool calls, tool outputs'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='tools_config',
            field=models.JSONField(blank=True, default=dict, help_text='Cấu hình công cụ mà agent có thể sử dụng (VD: prescription_tool, lab_order_tool)'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('CONSULTANT', 'Consultant'), ('TRIAGE', 'Triage'), ('CLINICAL', 'Clinical'), ('CORE', 'Core'), ('PHARMACIST', 'Pharmacist'), ('PARACLINICAL', 'Paraclinical')], default='CORE', max_length=20),
        ),
    ]
