# Generated by Django 5.2.9 on 2026-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_vectorstore_dimensions_vectorstore_embedding_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('CONSULTANT', 'Consultant'), ('TRIAGE', 'Triage'), ('CLINICAL', 'Clinical'), ('PHARMACY', 'Pharmacy'), ('PARACLINICAL', 'Paraclinical'), ('MARKETING', 'Marketing'), ('HUMAN_INTERVENTION', 'Human Intervention'), ('CORE', 'Core')], default='CORE', max_length=20),
        ),
    ]
