# Generated by Django 5.2.9 on 2026-03-08 08:02

import apps.ai_engine.agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='model_name',
            field=models.CharField(choices=[('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default=apps.ai_engine.agents.models.AgentProfile._default_model, max_length=50),
        ),
    ]
