# Generated by Django 5.2.9 on 2026-02-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_phone_nullable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
