# Generated by Django 5.2.9 on 2026-03-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
