# Generated by Django 5.2.9 on 2026-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('RIS_TECHNICIAN', 'RIS Technician'), ('LIS_TECHNICIAN', 'LIS Technician'), ('PHARMACIST', 'Pharmacist'), ('BILLING', 'Billing'), ('AI_AGENT', 'AI Agent')], max_length=20),
        ),
    ]
