# Generated by Django 5.2.9 on 2026-01-30 07:22

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='Công thức máu, X-Quang Ngực...', max_length=255, verbose_name='Tên dịch vụ')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã dịch vụ')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(help_text='Lab, Imaging, Functional Probing', max_length=50, verbose_name='Loại')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('ORDERED', 'Đã chỉ định'), ('PROCESSING', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(default='ROUTINE', help_text='STAT, URGENT, ROUTINE', max_length=20)),
                ('clinical_note', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán sơ bộ/Lý do chỉ định')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='authentication.staff')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='paraclinical.servicelist')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='reception.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceResult',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('text_result', models.TextField(blank=True, null=True, verbose_name='Kết quả chữ')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Link ảnh (DICOM/JPG)')),
                ('dicom_series_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_analysis_json', models.JSONField(blank=True, null=True, verbose_name='AI phân tích')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='paraclinical.serviceorder')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_services', to='authentication.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
