# Generated by Django 5.2.9 on 2026-03-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paraclinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('DRAFT', 'Nháp'), ('ORDERED', 'Đã chỉ định'), ('PROCESSING', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy')], default='UNPAID', max_length=20),
        ),
    ]
