# Generated by Django 5.2.9 on 2026-02-02 01:24

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã kỹ thuật')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kỹ thuật')),
                ('body_part', models.CharField(help_text='VD: Ngực, Bụng, Đầu, Cột sống...', max_length=100, verbose_name='Vùng chụp')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá tiền')),
                ('preparation', models.TextField(blank=True, help_text='VD: Nhịn ăn 6h, uống thuốc cản quang...', null=True, verbose_name='Hướng dẫn chuẩn bị')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kỹ thuật CĐHA',
                'verbose_name_plural': 'Các kỹ thuật CĐHA',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(help_text='VD: XR, CT, MRI, US', max_length=20, unique=True, verbose_name='Mã loại máy')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại máy')),
                ('room_location', models.CharField(blank=True, help_text='VD: Tầng 2 - Phòng 201', max_length=100, null=True, verbose_name='Vị trí phòng')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá cơ bản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('turnaround_time', models.IntegerField(blank=True, help_text='Thời gian dự kiến để có kết quả đọc', null=True, verbose_name='Thời gian trả kết quả (phút)')),
            ],
            options={
                'verbose_name': 'Loại thiết bị CĐHA',
                'verbose_name_plural': 'Các loại thiết bị CĐHA',
            },
        ),
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('clinical_indication', models.TextField(help_text='Mô tả triệu chứng hoặc chẩn đoán để bác sĩ CĐHA tham khảo', verbose_name='Lý do chỉ định/Chẩn đoán lâm sàng')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian chỉ định')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hẹn chụp')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thực hiện'), ('SCHEDULED', 'Đã lên lịch'), ('IN_PROGRESS', 'Đang chụp'), ('COMPLETED', 'Đã chụp, chờ đọc'), ('REPORTED', 'Đã có kết quả'), ('VERIFIED', 'Đã duyệt kết quả'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('NORMAL', 'Bình thường'), ('URGENT', 'Khẩn'), ('STAT', 'Cấp cứu')], default='NORMAL', max_length=20, verbose_name='Độ ưu tiên')),
                ('price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá lúc chỉ định')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders_created', to='authentication.staff', verbose_name='Bác sĩ chỉ định')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='patients.patient', verbose_name='Bệnh nhân')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='reception.visit', verbose_name='Lượt khám')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ris.imagingprocedure', verbose_name='Kỹ thuật chụp')),
            ],
            options={
                'verbose_name': 'Phiếu chỉ định CĐHA',
                'verbose_name_plural': 'Các phiếu chỉ định CĐHA',
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='ImagingExecution',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('execution_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thực hiện')),
                ('machine_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã máy chụp')),
                ('dicom_study_uid', models.CharField(blank=True, help_text='UID để link với PACS server', max_length=100, null=True, verbose_name='DICOM Study UID')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='URL ảnh preview')),
                ('execution_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú khi chụp')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_executed', to='authentication.staff', verbose_name='Kỹ thuật viên thực hiện')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='ris.imagingorder', verbose_name='Phiếu chỉ định')),
            ],
            options={
                'verbose_name': 'Thực hiện chụp',
                'verbose_name_plural': 'Các lần thực hiện chụp',
            },
        ),
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('findings', models.TextField(help_text='Chi tiết những gì quan sát được trên phim', verbose_name='Mô tả hình ảnh')),
                ('conclusion', models.TextField(help_text='Kết luận chẩn đoán của bác sĩ CĐHA', verbose_name='Kết luận')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Đề xuất/Khuyến nghị')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đọc kết quả')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã duyệt')),
                ('verified_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='Bất thường')),
                ('is_critical', models.BooleanField(default=False, help_text='Cần báo ngay cho bác sĩ lâm sàng', verbose_name='Nguy hiểm (Critical)')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ris.imagingorder', verbose_name='Phiếu chỉ định')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports', to='authentication.staff', verbose_name='Bác sĩ đọc kết quả')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_results_verified', to='authentication.staff', verbose_name='Bác sĩ duyệt')),
            ],
            options={
                'verbose_name': 'Kết quả CĐHA',
                'verbose_name_plural': 'Các kết quả CĐHA',
            },
        ),
        migrations.AddField(
            model_name='imagingprocedure',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='ris.modality', verbose_name='Loại máy'),
        ),
    ]
