# Generated by Django 5.2.9 on 2026-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingorder',
            name='accession_number',
            field=models.CharField(blank=True, help_text='Accession Number dùng để match với DICOM study từ Orthanc', max_length=64, null=True, unique=True, verbose_name='Mã chỉ định CLS'),
        ),
    ]
