# Generated by Django 5.2.9 on 2026-03-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris', '0002_add_accession_number_to_imaging_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingexecution',
            name='orthanc_instance_id',
            field=models.CharField(blank=True, help_text='ID của instance đầu tiên/chính để lấy preview', max_length=100, null=True, verbose_name='Orthanc Instance ID'),
        ),
    ]
