# Generated by Django 5.2.9 on 2026-02-02 01:24

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('departments', '0001_initial'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('bed_number', models.CharField(max_length=10, verbose_name='Số giường')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Trống'), ('OCCUPIED', 'Đang nằm'), ('RESERVED', 'Đã đặt trước'), ('CLEANING', 'Đang dọn'), ('MAINTENANCE', 'Bảo trì'), ('OUT_OF_SERVICE', 'Ngừng sử dụng')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Giường bệnh',
                'verbose_name_plural': 'Các giường bệnh',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('room_number', models.CharField(max_length=20, verbose_name='Số phòng')),
                ('room_type', models.CharField(choices=[('STANDARD', 'Thường'), ('VIP', 'VIP'), ('ICU', 'Hồi sức tích cực'), ('NICU', 'Hồi sức sơ sinh'), ('ISOLATION', 'Cách ly')], default='STANDARD', max_length=20, verbose_name='Loại phòng')),
                ('total_beds', models.IntegerField(default=4, verbose_name='Số giường tối đa')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá phòng/ngày')),
                ('has_bathroom', models.BooleanField(default=True, verbose_name='Có toilet riêng')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Có điều hòa')),
            ],
            options={
                'verbose_name': 'Phòng bệnh',
                'verbose_name_plural': 'Các phòng bệnh',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('admission_number', models.CharField(max_length=50, unique=True, verbose_name='Số hồ sơ nhập viện')),
                ('admission_time', models.DateTimeField(verbose_name='Thời gian nhập viện')),
                ('admission_diagnosis', models.TextField(verbose_name='Chẩn đoán lúc nhập viện')),
                ('discharge_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất viện')),
                ('discharge_diagnosis', models.TextField(blank=True, null=True, verbose_name='Chẩn đoán lúc xuất viện')),
                ('discharge_summary', models.TextField(blank=True, null=True, verbose_name='Tóm tắt bệnh án')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang điều trị'), ('DISCHARGED', 'Đã xuất viện'), ('TRANSFERRED', 'Đã chuyển viện'), ('DECEASED', 'Tử vong')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('transfer_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú chuyển khoa/giường')),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions_admitted', to='authentication.staff', verbose_name='Bác sĩ nhập viện')),
                ('discharging_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_discharged', to='authentication.staff', verbose_name='Bác sĩ xuất viện')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient', verbose_name='Bệnh nhân')),
                ('visit', models.ForeignKey(blank=True, help_text='Lượt khám ngoại trú dẫn đến nhập viện (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='reception.visit', verbose_name='Lượt khám gốc')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='inpatients.bed', verbose_name='Giường')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhập viện',
                'verbose_name_plural': 'Các hồ sơ nhập viện',
                'ordering': ['-admission_time'],
            },
        ),
        migrations.CreateModel(
            name='BedTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('transfer_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian chuyển')),
                ('reason', models.TextField(verbose_name='Lý do chuyển')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_transfers', to='inpatients.admission', verbose_name='Hồ sơ nhập viện')),
                ('from_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='inpatients.bed', verbose_name='Giường cũ')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_transfers_ordered', to='authentication.staff', verbose_name='Bác sĩ chỉ định')),
                ('to_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='inpatients.bed', verbose_name='Giường mới')),
            ],
            options={
                'verbose_name': 'Chuyển giường',
                'verbose_name_plural': 'Lịch sử chuyển giường',
                'ordering': ['-transfer_time'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='inpatients.room', verbose_name='Phòng'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100, verbose_name='Tên khoa nội trú')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khoa')),
                ('total_beds', models.IntegerField(default=0, verbose_name='Tổng số giường')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tầng')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='departments.department', verbose_name='Khoa')),
            ],
            options={
                'verbose_name': 'Khoa nội trú',
                'verbose_name_plural': 'Các khoa nội trú',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inpatients.ward', verbose_name='Khoa'),
        ),
        migrations.CreateModel(
            name='DailyCare',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('care_date', models.DateField(verbose_name='Ngày')),
                ('progress_note', models.TextField(help_text='Tình trạng bệnh nhân trong ngày', verbose_name='Diễn biến')),
                ('vital_signs', models.JSONField(blank=True, help_text="VD: {'blood_pressure': '120/80', 'heart_rate': 75, 'temperature': 37.0}", null=True, verbose_name='Dấu hiệu sinh tồn')),
                ('medication_orders', models.TextField(blank=True, null=True, verbose_name='Y lệnh thuốc')),
                ('nursing_orders', models.TextField(blank=True, null=True, verbose_name='Y lệnh chăm sóc')),
                ('lab_orders_note', models.TextField(blank=True, null=True, verbose_name='Chỉ định xét nghiệm')),
                ('imaging_orders_note', models.TextField(blank=True, null=True, verbose_name='Chỉ định CĐHA')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cares', to='inpatients.admission', verbose_name='Hồ sơ nhập viện')),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_cares_attended', to='authentication.staff', verbose_name='Bác sĩ điều trị')),
            ],
            options={
                'verbose_name': 'Tờ điều trị',
                'verbose_name_plural': 'Các tờ điều trị',
                'ordering': ['-care_date'],
                'unique_together': {('admission', 'care_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('ward', 'room_number')},
        ),
    ]
