# Generated by Django 5.2.9 on 2026-03-08 07:11

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_managers'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('allergen_name', models.CharField(help_text='Tên thuốc / thực phẩm / chất gây dị ứng (viết thường để so sánh dễ dàng)', max_length=255, verbose_name='Tên chất gây dị ứng')),
                ('allergen_name_normalized', models.CharField(db_index=True, help_text='Tự động tạo từ allergen_name.lower().strip() khi lưu', max_length=255, verbose_name='Tên chuẩn hóa (lowercase)')),
                ('allergen_type', models.CharField(choices=[('DRUG', 'Thuốc'), ('FOOD', 'Thực phẩm'), ('ENV', 'Môi trường (phấn hoa, bụi...)'), ('OTHER', 'Khác')], default='DRUG', max_length=10, verbose_name='Loại dị ứng')),
                ('severity', models.CharField(choices=[('MILD', 'Nhẹ (nổi mẩn, ngứa)'), ('MODERATE', 'Trung bình (phù, khó thở nhẹ)'), ('SEVERE', 'Nặng (phù Quincke, khó thở nặng)'), ('LIFE_THREATENING', 'Đe dọa tính mạng (sốc phản vệ)')], default='MILD', max_length=20, verbose_name='Mức độ')),
                ('reaction_description', models.TextField(blank=True, help_text='Mô tả chi tiết triệu chứng khi tiếp xúc dị nguyên', null=True, verbose_name='Mô tả phản ứng')),
                ('confirmed_date', models.DateField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allergies', to='authentication.staff', verbose_name='Bác sĩ xác nhận')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient', verbose_name='Bệnh nhân')),
            ],
            options={
                'verbose_name': 'Dị ứng bệnh nhân',
                'verbose_name_plural': 'Danh sách dị ứng bệnh nhân',
                'indexes': [models.Index(fields=['patient', 'allergen_type'], name='allergy_patient_type_idx'), models.Index(fields=['allergen_name_normalized'], name='allergy_name_norm_idx')],
                'unique_together': {('patient', 'allergen_name_normalized')},
            },
        ),
    ]
