# Generated by Django 5.2.9 on 2026-02-09 06:34

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_user_managers'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã bảng giá')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bảng giá')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Bảng giá mặc định')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Áp dụng từ ngày')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Áp dụng đến ngày')),
            ],
            options={
                'verbose_name': 'Bảng giá',
                'verbose_name_plural': 'Các bảng giá',
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã dịch vụ')),
                ('name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('service_type', models.CharField(choices=[('CONSULTATION', 'Khám bệnh'), ('LAB', 'Xét nghiệm'), ('IMAGING', 'Chẩn đoán hình ảnh'), ('PROCEDURE', 'Thủ thuật'), ('SURGERY', 'Phẫu thuật'), ('MEDICATION', 'Thuốc'), ('SUPPLIES', 'Vật tư'), ('BED', 'Giường bệnh'), ('OTHER', 'Khác')], default='OTHER', max_length=20, verbose_name='Loại dịch vụ')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá cơ bản')),
                ('bhyt_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã BHYT')),
                ('bhyt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá BHYT thanh toán')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Danh mục dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='DepositPayment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Số phiếu tạm ứng')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền tạm ứng')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đã sử dụng')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ ngân hàng'), ('TRANSFER', 'Chuyển khoản'), ('MOMO', 'Ví MoMo'), ('VNPAY', 'VNPay'), ('INSURANCE', 'BHYT chi trả')], default='CASH', max_length=20, verbose_name='Phương thức')),
                ('deposit_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạm ứng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits_received', to='authentication.staff', verbose_name='Thu ngân')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='patients.patient', verbose_name='Bệnh nhân')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='reception.visit', verbose_name='Lượt khám')),
            ],
            options={
                'verbose_name': 'Tạm ứng',
                'verbose_name_plural': 'Các khoản tạm ứng',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Số hóa đơn')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Giảm giá')),
                ('insurance_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BHYT chi trả')),
                ('patient_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bệnh nhân phải trả')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đã thanh toán')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PARTIAL', 'Thanh toán một phần'), ('PAID', 'Đã thanh toán'), ('CANCELLED', 'Đã hủy'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to='authentication.staff', verbose_name='Người tạo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient', verbose_name='Bệnh nhân')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='reception.visit', verbose_name='Lượt khám')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.pricelist', verbose_name='Bảng giá áp dụng')),
            ],
            options={
                'verbose_name': 'Hóa đơn',
                'verbose_name_plural': 'Các hóa đơn',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Số phiếu thu')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('CARD', 'Thẻ ngân hàng'), ('TRANSFER', 'Chuyển khoản'), ('MOMO', 'Ví MoMo'), ('VNPAY', 'VNPay'), ('INSURANCE', 'BHYT chi trả')], default='CASH', max_length=20, verbose_name='Phương thức')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thanh toán')),
                ('is_refund', models.BooleanField(default=False, verbose_name='Là hoàn tiền')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Lý do hoàn tiền')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='authentication.staff', verbose_name='Thu ngân')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice', verbose_name='Hóa đơn')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Các khoản thanh toán',
                'ordering': ['-payment_time'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('item_name', models.CharField(max_length=255, verbose_name='Tên mục')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Thành tiền')),
                ('insurance_covered', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='BHYT thanh toán')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('related_order_type', models.CharField(blank=True, help_text='VD: LAB_ORDER, IMAGING_ORDER, PRESCRIPTION', max_length=50, null=True, verbose_name='Loại phiếu gốc')),
                ('related_order_id', models.UUIDField(blank=True, null=True, verbose_name='ID phiếu gốc')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice', verbose_name='Hóa đơn')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.servicecatalog', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Chi tiết hóa đơn',
                'verbose_name_plural': 'Chi tiết hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='billing.pricelist', verbose_name='Bảng giá')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.servicecatalog', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Giá dịch vụ',
                'verbose_name_plural': 'Giá dịch vụ',
                'unique_together': {('service', 'price_list')},
            },
        ),
    ]
