# Generated by Django 5.2.9 on 2026-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_managers'),
        ('billing', '0001_initial'),
        ('patients', '0002_remove_patient_address_patient_address_detail_and_more'),
        ('reception', '0008_visit_pending_merge'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['visit', 'status'], name='invoice_visit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient'], name='invoice_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payment_invoice_idx'),
        ),
    ]
