# Generated by Django 5.2.9 on 2026-02-24 13:44

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRServerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='VD: BHXH Gateway, Liên viện Server', max_length=100, verbose_name='Tên cấu hình')),
                ('base_url', models.URLField(help_text='VD: https://fhir.example.com/r4', verbose_name='FHIR Server URL')),
                ('fhir_version', models.CharField(default='R4', max_length=10, verbose_name='Phiên bản FHIR')),
                ('auth_type', models.CharField(choices=[('NONE', 'Không xác thực'), ('BEARER', 'Bearer Token'), ('BASIC', 'Basic Auth'), ('OAUTH2', 'OAuth2 Client Credentials')], default='NONE', max_length=20, verbose_name='Loại xác thực')),
                ('auth_token', models.TextField(blank=True, help_text='Bearer token hoặc base64(user:pass)', null=True, verbose_name='Token / Credentials')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='Timeout (giây)')),
            ],
            options={
                'verbose_name': 'Cấu hình FHIR Server',
                'verbose_name_plural': 'Cấu hình FHIR Server',
            },
        ),
        migrations.CreateModel(
            name='PACSConfig',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='VD: Orthanc chính, dcm4chee backup', max_length=100, verbose_name='Tên PACS')),
                ('base_url', models.URLField(help_text='VD: https://pacs.example.com/dicom-web', verbose_name='DICOMweb Base URL')),
                ('ae_title', models.CharField(default='HIS_AIO', help_text='Application Entity Title (tối đa 16 ký tự)', max_length=16, verbose_name='AE Title')),
                ('auth_type', models.CharField(choices=[('NONE', 'Không xác thực'), ('BEARER', 'Bearer Token'), ('BASIC', 'Basic Auth')], default='NONE', max_length=20, verbose_name='Loại xác thực')),
                ('auth_token', models.TextField(blank=True, null=True, verbose_name='Token / Credentials')),
                ('timeout_seconds', models.IntegerField(default=60, verbose_name='Timeout (giây)')),
                ('wado_rs_path', models.CharField(default='/wado-rs', max_length=100, verbose_name='WADO-RS Path')),
                ('stow_rs_path', models.CharField(default='/stow-rs', max_length=100, verbose_name='STOW-RS Path')),
                ('qido_rs_path', models.CharField(default='/qido-rs', max_length=100, verbose_name='QIDO-RS Path')),
            ],
            options={
                'verbose_name': 'Cấu hình PACS Server',
                'verbose_name_plural': 'Cấu hình PACS Server',
            },
        ),
        migrations.CreateModel(
            name='InteropAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direction', models.CharField(choices=[('OUT', 'Gửi đi (Export)'), ('IN', 'Nhận về (Import)')], max_length=3, verbose_name='Chiều trao đổi')),
                ('protocol', models.CharField(choices=[('FHIR', 'HL7 FHIR'), ('DICOM', 'DICOM')], max_length=5, verbose_name='Giao thức')),
                ('resource_type', models.CharField(help_text='VD: Patient, Encounter, ImagingStudy', max_length=50, verbose_name='Loại tài nguyên')),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID tài nguyên')),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('PARTIAL', 'Thành công một phần')], max_length=10, verbose_name='Trạng thái')),
                ('remote_server', models.CharField(blank=True, max_length=255, null=True, verbose_name='Server đích/nguồn')),
                ('request_payload_size', models.IntegerField(blank=True, null=True, verbose_name='Kích thước request (bytes)')),
                ('response_payload_size', models.IntegerField(blank=True, null=True, verbose_name='Kích thước response (bytes)')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='Thời gian xử lý (ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Thông báo lỗi')),
                ('initiated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Người/Hệ thống khởi tạo')),
            ],
            options={
                'verbose_name': 'Nhật ký liên thông',
                'verbose_name_plural': 'Nhật ký liên thông',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['protocol', 'resource_type'], name='interoperab_protoco_791cc9_idx'), models.Index(fields=['status', 'timestamp'], name='interoperab_status_c10ef4_idx')],
            },
        ),
    ]
