# Generated by Django 5.2.9 on 2026-01-30 07:22

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255, verbose_name='Tên thuốc')),
                ('active_ingredient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hoạt chất')),
                ('usage_route', models.CharField(blank=True, help_text='Uống, Tiêm, Bôi...', max_length=50, null=True, verbose_name='Đường dùng')),
                ('inventory_count', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('unit', models.CharField(default='Viên', max_length=50, verbose_name='Đơn vị tính')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Lời dặn bác sĩ')),
                ('ai_interaction_warning', models.TextField(blank=True, help_text='Cảnh báo tương tác thuốc từ AI', null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_prescribed', to='authentication.staff')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='reception.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('usage_instruction', models.CharField(help_text='Sáng 1, Chiều 1...', max_length=255, verbose_name='Cách dùng')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_details', to='pharmacy.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pharmacy.prescription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
