# Generated by Django 5.2.9 on 2026-02-02 01:24

import django.db.models.deletion
import uuid6
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('pharmacy', '0001_initial'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nhóm thuốc',
                'verbose_name_plural': 'Các nhóm thuốc',
            },
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Thuốc', 'verbose_name_plural': 'Danh mục thuốc'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Đơn thuốc', 'verbose_name_plural': 'Các đơn thuốc'},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondetail',
            options={'verbose_name': 'Chi tiết đơn thuốc', 'verbose_name_plural': 'Chi tiết đơn thuốc'},
        ),
        migrations.AddField(
            model_name='medication',
            name='code',
            field=models.CharField(default='MED000', max_length=50, unique=True, verbose_name='Mã thuốc'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='VD: Viên nén, Viên nang, Dung dịch', max_length=50, null=True, verbose_name='Dạng bào chế'),
        ),
        migrations.AddField(
            model_name='medication',
            name='min_stock',
            field=models.IntegerField(default=10, verbose_name='Tồn kho tối thiểu'),
        ),
        migrations.AddField(
            model_name='medication',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá nhập'),
        ),
        migrations.AddField(
            model_name='medication',
            name='requires_prescription',
            field=models.BooleanField(default=True, verbose_name='Cần đơn thuốc'),
        ),
        migrations.AddField(
            model_name='medication',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá bán'),
        ),
        migrations.AddField(
            model_name='medication',
            name='strength',
            field=models.CharField(blank=True, help_text='VD: 500mg, 10mg/ml', max_length=100, null=True, verbose_name='Hàm lượng'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Chẩn đoán'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_code',
            field=models.CharField(default='PRES-OLD', max_length=50, unique=True, verbose_name='Mã đơn thuốc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày kê đơn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ phát thuốc'), ('PARTIAL', 'Đã phát một phần'), ('DISPENSED', 'Đã phát thuốc'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='dispensed_quantity',
            field=models.IntegerField(default=0, verbose_name='Đã phát'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số ngày dùng'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_prescribed', to='authentication.staff', verbose_name='Bác sĩ kê đơn'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='reception.visit', verbose_name='Lượt khám'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_details', to='pharmacy.medication', verbose_name='Thuốc'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='pharmacy.prescription', verbose_name='Đơn thuốc'),
        ),
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='pharmacy.drugcategory', verbose_name='Nhóm thuốc'),
        ),
        migrations.CreateModel(
            name='MedicationLot',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('lot_number', models.CharField(max_length=50, verbose_name='Số lô')),
                ('expiry_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Ngày sản xuất')),
                ('initial_quantity', models.IntegerField(default=0, verbose_name='Số lượng nhập')),
                ('remaining_quantity', models.IntegerField(default=0, verbose_name='Số lượng còn lại')),
                ('import_date', models.DateField(verbose_name='Ngày nhập')),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá nhập')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà cung cấp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacy.medication', verbose_name='Thuốc')),
            ],
            options={
                'verbose_name': 'Lô thuốc',
                'verbose_name_plural': 'Các lô thuốc',
                'ordering': ['expiry_date'],
                'unique_together': {('medication', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(verbose_name='Số lượng xuất')),
                ('dispense_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xuất')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses_performed', to='authentication.staff', verbose_name='Dược sĩ phát thuốc')),
                ('prescription_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='pharmacy.prescriptiondetail', verbose_name='Chi tiết đơn')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='pharmacy.medicationlot', verbose_name='Lô thuốc')),
            ],
            options={
                'verbose_name': 'Phiếu xuất thuốc',
                'verbose_name_plural': 'Các phiếu xuất thuốc',
            },
        ),
    ]
