# Generated by Django 5.2.9 on 2026-02-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_drugcategory_alter_medication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã thuốc'),
        ),
    ]
