# Generated by Django 5.2.9 on 2026-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_managers'),
        ('pharmacy', '0003_alter_medication_code'),
        ('reception', '0008_visit_pending_merge'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescription_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['visit', 'status'], name='prescription_visit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiondetail',
            index=models.Index(fields=['prescription'], name='prescdetail_prescription_idx'),
        ),
    ]
