# Generated by Django 5.2.9 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_prescription_prescription_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='atc_code',
            field=models.CharField(blank=True, help_text='Mã phân loại WHO-ATC (VD: N02BE01 cho Paracetamol)', max_length=10, null=True, verbose_name='Mã ATC (WHO)'),
        ),
        migrations.AddField(
            model_name='medication',
            name='national_drug_code',
            field=models.CharField(blank=True, help_text='Số đăng ký thuốc quốc gia do Bộ Y tế cấp (VD: VD-12345-13)', max_length=50, null=True, verbose_name='Mã số đăng ký (BYT)'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cdss_alerts',
            field=models.JSONField(blank=True, help_text='Kết quả CDSS: {allergy_alerts: [...], interaction_alerts: [...], has_critical: bool}', null=True),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a_name', models.CharField(help_text='Tên hoạt chất viết thường, sắp xếp A-Z so với drug_b_name', max_length=255, verbose_name='Hoạt chất A (lowercase)')),
                ('drug_b_name', models.CharField(max_length=255, verbose_name='Hoạt chất B (lowercase)')),
                ('severity', models.CharField(choices=[('MAJOR', 'Nghiêm trọng – KHÔNG dùng chung'), ('MODERATE', 'Trung bình – Cần theo dõi chặt chẽ'), ('MINOR', 'Nhẹ – Có thể dùng, lưu ý theo dõi')], default='MODERATE', max_length=10, verbose_name='Mức độ nghiêm trọng')),
                ('description', models.TextField(help_text='Cơ chế và hậu quả lâm sàng', verbose_name='Mô tả tương tác')),
                ('recommendation', models.TextField(help_text='Hướng dẫn xử trí: tránh dùng chung, theo dõi INR...', verbose_name='Khuyến nghị xử trí')),
                ('references', models.TextField(blank=True, help_text='Nguồn: DrugBank, Micromedex, BNF...', null=True, verbose_name='Tài liệu tham khảo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tương tác thuốc',
                'verbose_name_plural': 'Cơ sở dữ liệu tương tác thuốc',
                'ordering': ['-severity', 'drug_a_name'],
                'indexes': [models.Index(fields=['drug_a_name'], name='ddi_drug_a_idx'), models.Index(fields=['drug_b_name'], name='ddi_drug_b_idx'), models.Index(fields=['severity'], name='ddi_severity_idx')],
                'unique_together': {('drug_a_name', 'drug_b_name')},
            },
        ),
    ]
