# Generated by Django 5.2.9 on 2026-02-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Mô tả chi tiết chức năng khoa phòng'),
        ),
        migrations.AddField(
            model_name='department',
            name='specialties',
            field=models.TextField(blank=True, default='', help_text='Danh sách chuyên khoa, ngăn bởi dấu phẩy'),
        ),
        migrations.AddField(
            model_name='department',
            name='typical_symptoms',
            field=models.TextField(blank=True, default='', help_text='Triệu chứng thường gặp để AI phân loại khoa phòng'),
        ),
    ]
