# Generated by Django 5.2.9 on 2026-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordocument',
            name='collection',
            field=models.CharField(choices=[('clinical_records', 'Clinical Records'), ('icd10_codes', 'ICD-10 Codes'), ('drugs', 'Drugs & Interactions'), ('medical_protocols', 'Medical Protocols'), ('hospital_process', 'Hospital Process Q&A'), ('departments', 'Departments')], db_index=True, help_text='Collection type (clinical_records or icd10_codes)', max_length=50),
        ),
    ]
