# Generated by Django 5.2.9 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_service', '0002_alter_vectordocument_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordocument',
            name='collection',
            field=models.CharField(choices=[('clinical_records', 'Clinical Records'), ('icd10_codes', 'ICD-10 Codes'), ('drugs', 'Drugs & Interactions'), ('medical_protocols', 'Medical Protocols'), ('guidelines', 'Clinical Guidelines (Phác đồ điều trị)'), ('hospital_process', 'Hospital Process Q&A'), ('departments', 'Departments')], db_index=True, help_text='Collection type (clinical_records or icd10_codes)', max_length=50),
        ),
    ]
