# Generated by Django 5.2.9 on 2026-01-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('include', models.TextField(blank=True, null=True)),
                ('exclude', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mã ICD-10',
                'verbose_name_plural': 'Mã ICD-10',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ICD10Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('include', models.TextField(blank=True, null=True)),
                ('exclude', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.icd10category')),
            ],
            options={
                'verbose_name': 'Mã phụ ICD-10',
                'verbose_name_plural': 'Mã phụ ICD-10',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icd10_codes', to='core.icd10subcategory')),
            ],
            options={
                'verbose_name': 'Mã chi tiết ICD-10',
                'verbose_name_plural': 'Mã chi tiết ICD-10',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.province')),
            ],
            options={
                'verbose_name': 'Xã/Phường',
                'verbose_name_plural': 'Xã/Phường',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['province', 'code'], name='core_ward_provinc_6e8ab5_idx')],
            },
        ),
    ]
