# Generated by Django 5.2.9 on 2026-03-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD11Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Mã ICD-11 (ví dụ: CA40.0)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Tên bệnh ICD-11 (tiếng Anh)', max_length=500)),
                ('title_vi', models.CharField(blank=True, help_text='Tên bệnh ICD-11 (tiếng Việt)', max_length=500, null=True)),
                ('inclusions', models.TextField(blank=True, null=True)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('is_billable', models.BooleanField(default=True, help_text='Mã có thể dùng cho kê khai (leaf node)')),
                ('is_active', models.BooleanField(default=True)),
                ('icd10_map', models.ManyToManyField(blank=True, related_name='icd11_codes', to='core.icd10code', verbose_name='Mã ICD-10 tương đương')),
            ],
            options={
                'verbose_name': 'Mã ICD-11',
                'verbose_name_plural': 'Mã ICD-11',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Mã dịch vụ kỹ thuật (mã BYT)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Tên dịch vụ')),
                ('group', models.CharField(choices=[('XN', 'Xét nghiệm'), ('CDHA', 'Chẩn đoán hình ảnh'), ('PT', 'Phẫu thuật thủ thuật'), ('PHCN', 'Phục hồi chức năng'), ('KCB', 'Khám chữa bệnh'), ('KHAC', 'Khác')], default='KHAC', max_length=10, verbose_name='Nhóm dịch vụ')),
                ('unit', models.CharField(default='lần', max_length=50, verbose_name='Đơn vị tính')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá thu (VNĐ)')),
                ('bhyt_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá BHYT thanh toán')),
                ('is_covered_by_bhyt', models.BooleanField(default=False, verbose_name='BHYT chi trả')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dịch vụ kỹ thuật',
                'verbose_name_plural': 'Danh mục dịch vụ kỹ thuật',
                'ordering': ['group', 'code'],
                'indexes': [models.Index(fields=['group', 'code'], name='core_techni_group_657897_idx')],
            },
        ),
    ]
