# Generated by Django 5.2.9 on 2026-01-31 14:30

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('departments', '0001_initial'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(help_text='VD: PK01, LIS01, PHARMACY01', max_length=20, unique=True, verbose_name='Mã điểm dịch vụ')),
                ('name', models.CharField(max_length=100, verbose_name='Tên điểm dịch vụ')),
                ('station_type', models.CharField(choices=[('RECEPTION', 'Tiếp đón'), ('TRIAGE', 'Phân luồng'), ('DOCTOR', 'Phòng khám bác sĩ'), ('LIS', 'Phòng xét nghiệm (Lấy mẫu)'), ('RIS', 'Phòng chẩn đoán hình ảnh'), ('PHARMACY', 'Nhà thuốc'), ('CASHIER', 'Thu ngân')], max_length=20, verbose_name='Loại điểm')),
                ('room_location', models.CharField(blank=True, help_text='VD: Tầng 1 - Dãy A', max_length=100, null=True, verbose_name='Vị trí phòng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('current_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stations', to='authentication.staff', verbose_name='Nhân viên phụ trách')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_stations', to='departments.department', verbose_name='Khoa/Phòng')),
            ],
            options={
                'verbose_name': 'Điểm dịch vụ',
                'verbose_name_plural': 'Các điểm dịch vụ',
                'ordering': ['station_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QueueNumber',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('number_code', models.CharField(help_text='VD: PK01-2026013101-005', max_length=30, unique=True, verbose_name='Mã số thứ tự')),
                ('daily_sequence', models.IntegerField(verbose_name='Số thứ tự trong ngày')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_numbers', to='reception.visit', verbose_name='Lượt khám')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_numbers', to='qms.servicestation', verbose_name='Điểm dịch vụ')),
            ],
            options={
                'verbose_name': 'Số thứ tự',
                'verbose_name_plural': 'Các số thứ tự',
                'ordering': ['created_date', 'daily_sequence'],
                'unique_together': {('station', 'created_date', 'daily_sequence')},
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('WAITING', 'Đang chờ'), ('CALLED', 'Đã gọi'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Hoàn thành'), ('SKIPPED', 'Bỏ qua'), ('NO_SHOW', 'Không có mặt')], default='WAITING', max_length=20, verbose_name='Trạng thái')),
                ('entered_queue_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian vào hàng đợi')),
                ('called_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gọi')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu phục vụ')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('priority', models.IntegerField(default=0, help_text='Số càng cao càng ưu tiên (VD: Cấp cứu=10, Người già=5, Thường=0)', verbose_name='Độ ưu tiên')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('queue_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='qms.queuenumber', verbose_name='Số thứ tự')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='qms.servicestation', verbose_name='Điểm dịch vụ')),
            ],
            options={
                'verbose_name': 'Phiếu xếp hàng',
                'verbose_name_plural': 'Các phiếu xếp hàng',
                'ordering': ['-priority', 'entered_queue_time'],
            },
        ),
    ]
