# Generated by Django 5.2.9 on 2026-02-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_time_slot_end'),
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='booking_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='appointments.appointment', verbose_name='Lịch hẹn gốc'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='source_type',
            field=models.CharField(choices=[('WALK_IN', 'Vãng lai'), ('ONLINE_BOOKING', 'Đặt lịch từ xa'), ('EMERGENCY', 'Cấp cứu')], default='WALK_IN', max_length=20, verbose_name='Nguồn vào hàng chờ'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='priority',
            field=models.IntegerField(default=0, help_text='Emergency=100, Booking đúng giờ=7, Booking trễ=3, Walk-in=0', verbose_name='Độ ưu tiên'),
        ),
    ]
