# Generated by Django 5.2.9 on 2026-01-22 15:12

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('core', '0001_initial'),
        ('reception', '0002_remove_visit_ai_prediction_remove_visit_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('chief_complaint', models.TextField(help_text='Lý do vào viện/Triệu chứng chính')),
                ('history_of_present_illness', models.TextField(help_text='Bệnh sử')),
                ('physical_exam', models.TextField(help_text='Khám lâm sàng')),
                ('r_agent_summary', models.JSONField(blank=True, null=True)),
                ('d_agent_summary', models.JSONField(blank=True, null=True)),
                ('c_agent_summary', models.JSONField(blank=True, null=True)),
                ('medical_summary', models.TextField(blank=True, null=True)),
                ('final_diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records', to='authentication.staff')),
                ('main_icd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_records', to='core.icd10code', verbose_name='Bệnh chính (ICD-10)')),
                ('sub_icds', models.ManyToManyField(blank=True, related_name='sub_records', to='core.icd10code', verbose_name='Bệnh kèm theo')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='reception.visit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
