# Generated by Django 5.2.9 on 2026-01-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalrecord',
            old_name='c_agent_summary',
            new_name='clinical_agent_summary',
        ),
        migrations.RenameField(
            model_name='clinicalrecord',
            old_name='d_agent_summary',
            new_name='core_agent_summary',
        ),
        migrations.RenameField(
            model_name='clinicalrecord',
            old_name='r_agent_summary',
            new_name='triage_agent_summary',
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='vital_signs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
