# Generated by Django 5.2.9 on 2026-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_rename_c_agent_summary_clinicalrecord_clinical_agent_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='ai_suggestion_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Gợi ý thô từ AI'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn tất khám'),
        ),
    ]
