# Generated by Django 5.2.9 on 2026-01-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('core', '0001_initial'),
        ('emr', '0003_clinicalrecord_ai_suggestion_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_records', to='authentication.staff'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='final_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='history_of_present_illness',
            field=models.TextField(blank=True, help_text='Bệnh sử', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='main_icd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_records', to='core.icd10code', verbose_name='Bệnh chính (ICD-10)'),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='physical_exam',
            field=models.TextField(blank=True, help_text='Khám lâm sàng', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalrecord',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
