# Generated by Django 5.2.9 on 2026-03-08 07:11

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_icd11code_technicalservice'),
        ('emr', '0004_alter_clinicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalGuideline',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='VD: Phác đồ điều trị tăng huyết áp - BYT 2024', max_length=500, verbose_name='Tên phác đồ')),
                ('content', models.TextField(help_text='Nội dung đầy đủ (Markdown/plain text). Dùng để embed vào RAG.', verbose_name='Nội dung phác đồ')),
                ('version', models.CharField(help_text='VD: 2024-BYT-Rev3', max_length=50, verbose_name='Phiên bản')),
                ('source', models.CharField(help_text='VD: Bộ Y tế 2024, Hội tim mạch học Việt Nam', max_length=255, verbose_name='Nguồn')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Ngày hiệu lực')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ những phác đồ is_active=True mới được nạp vào RAG', verbose_name='Đang sử dụng')),
                ('icd10_codes', models.ManyToManyField(blank=True, help_text='Các mã bệnh mà phác đồ này áp dụng', related_name='guidelines', to='core.icd10code', verbose_name='Mã ICD-10 liên quan')),
            ],
            options={
                'verbose_name': 'Phác đồ điều trị',
                'verbose_name_plural': 'Danh mục phác đồ điều trị',
                'ordering': ['-effective_date', 'title'],
                'indexes': [models.Index(fields=['is_active', 'effective_date'], name='guideline_active_date_idx')],
            },
        ),
    ]
