# Generated by Django 5.2.9 on 2026-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0005_clinicalguideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='pre_triage_summary',
            field=models.TextField(blank=True, help_text='Toàn bộ tóm tắt bệnh án từ Summarize Agent sau khi bệnh nhân đăng ký kiosk', null=True, verbose_name='Tóm tắt tiền phân luồng'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='triage_hints',
            field=models.TextField(blank=True, help_text='Tóm tắt ngắn từ Summarize Agent để Agent Triage chú ý (VD: BN THA mạn - chú BP_SYS)', null=True, verbose_name='Lời nhắc cho Agent Phân Luồng'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='vital_sign_recommendations',
            field=models.JSONField(blank=True, help_text='Danh sách key chỉ số SH Summarize Agent khuyến nghị (VD: ["spo2", "bp_systolic"])', null=True, verbose_name='Chỉ số SH được AI đề xuất thu thập'),
        ),
    ]
